### ISSUE TITLE
Filtering with nb of holes >0

### ISSUE THREAD

**Issue by dhreignier** [benzAI-team/BenzAI#6]
The filtering on the nb of holes does not appear to be efficient:
Example : @generation : nb pf hex <=8 & nb of holes > 0 returns 1 structure
Filtering this structure with  nb of holes > 0 takes 121 seconds!

**Comment by nprcovic** [comment]
The constraint 'holes > x' was handled as if it was 'holes >= x' when computing the size of the search space. I have fixed this bug and now you should have your solution within a second.
More generally, please be more precise when setting your bounds in order to help the solver filtering impossible solutions. When you know the upper and/or lower bounds, give it as a constraint. In the example you gave, 'holes = 1' gave faster results since the solver can make some optimizations according to an upper bound and (independantly) according to a lower bound.
